WELCOME TO THE RABBIT FARM.
A DARK ENTITY HAS CORRUPTED OUR FARMERS' MINDS; THEY HAVE TURNED VIOLENT.
PRESS E TO TAKE YOUR SWORD AND LEFT CLICK TO STRIKE. <> 
TO ATTACK IN A PROPER WAY YOU MUST STOP... <>
IS A FEATURE EHM... TO MAKE THE GAME HARDER... YES...
HEART WILL HEAL YOUR LIFE BY 20HP
WHEN HITTED THE ENEMY WILL VANISH. <>
COME BACK TO ME ONCE THE FARM IS CLEARED.