-> main

=== main ====
AHHH
OH NO MY GARDEN! YOU DESTROY EVERYTHING!
WILL YOU DO ME A FAVOR? IN THAT TIME I WILL REPAIR YOU SPACESHIP.
YOU HAVE NO CHOICE IN ANYCASE. 
FIND THE FIRST PORTAL AND HELP PEOPLE IN THERE. 
BRING ME PIECES TO REPAIR YOUR SHIP OR OTHER TECHNOLOGIES AND I WILL UPGRADE YOU!
-> END